[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
scoogi_battle = "7ftEA2QYxQsfBFZYiyXfA43iLvLoLmdJ6kwkmCUkGxVY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test.validator]
bind_address = "127.0.0.1"
